config/routes.rb
Rails.application.routes.draw do
  # root 'admin#index'
  resources :admin
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    Product.create(product_params)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    # binding.pry
    product = Product.find(params[:id])
    product.update(product_params)

    redirect_to('/admin')
  end

  private
    def product_params
      params.require(:product).permit(:name, :image, :price)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/edit.html.erb
<div class="container">
  <div class="d-flex align-items-center">
    <h1>商品情報を変更する</h1>
    <div class="ml-auto boards__linkBox">
      <%= link_to '商品一覧', admin_index_path, class: 'btn btn-outline-dark' %>
    </div>
  </div>
  <%= form_with model: @product, url: admin_path, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :image, '画像' %>
      <div>
        <% if @product.image? %>
          <%= image_tag @product.image.url %>
        <% else %>
          <%= image_tag "noimage.png" %>
        <% end %>
      </div>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :price, '料金' %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>
    <%= f.submit '保存', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'admin' %>
<% end %>

<div class="container">
  <div class="d-flex align-items-center">
    <h1>商品一覧</h1>
    <div class="ml-auto productList__linkBox">
      <%= link_to '新規作成', new_admin_path, class: 'btn btn-outline-dark' %>
    </div>
  </div>
  <table class="table table-hover productList__table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>商品名</th>
        <th>画像</th>
        <th>料金</th>
        <th>作成日時</th>
        <th>更新日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.name %></td>
          <td class="productList__img">
            <% if product.image? %>
              <%= image_tag product.image.url %>
            <% else %>
              <%= image_tag "noimage.png" %>
            <% end %>
          </td>
          <td><%= product.price %>円</td>
          <td><%= product.created_at.to_s(:datetime_jp) %></td>
          <td><%= product.updated_at.to_s(:datetime_jp) %></td>
          <td><%= link_to '詳細', admin_path(product.id), class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div><!-- container -->

app/views/admin/new.html.erb
<div class="container">
  <div class="d-flex align-items-center">
    <h1>商品登録</h1>
    <div class="ml-auto boards__linkBox">
      <a href="/admin" class="btn btn-outline-dark">商品一覧</a>
    </div>
  </div>
  <%= form_with model: @product, url: admin_url do |f| %>
    <div class="form-group">
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :image, '画像' %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :price, '料金' %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>
    <%= f.submit '保存', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'admin' %>
<% end %>

<div class="container">
  <div class="d-flex align-items-center mt-4 mb-4">
    <div class="ml-auto boards__linkBox">
      <%= link_to '一覧', admin_index_path, class: 'btn btn-outline-dark' %>
      <%= link_to '編集', edit_admin_path, class: 'btn btn-outline-dark' %>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h4><%= @product.name %></h4>
    </div>
    <div class="card-body">
      <p class="card-img">
        <% if @product.image? %>
          <%= image_tag @product.image.url %>
        <% else %>
          <%= image_tag "noimage.png" %>
        <% end %>
      </p>
      <p class="font-weight-bold mr-10">
        <%= @product.price %>円
      </p>
    </div>
  </div></div><!-- container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>